name: Production Android Build
on:
  push:
    branches:
      - deployment

jobs:
  build:
    name: Production Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Increase system limits to prevent ENOSPC errors
      - name: Configure System Limits
        run: |
          sudo sysctl -w fs.inotify.max_user_watches=524288
          sudo sysctl -w fs.inotify.max_queued_events=524288
          sudo sysctl -w fs.inotify.max_user_instances=524288

      # Configure EAS credentials
      - name: Configure EAS Credentials
        run: |
          eas credentials --platform android --profile production --non-interactive

      - name: Build Production Android
        run: |
          eas build \
            --platform android \
            --profile production \
            --non-interactive --no-wait
